server:
  port: 8082
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springBatch
    username: root
    password: Ashish@2845
  jpa:
    hibernate:
      ddl-auto: update
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false